### ISSUE TITLE
Any plan for support of rxjs observables?

### ISSUE THREAD

**Issue by kevlarAdmin** [umbraco/Umbraco.Headless.Client.NodeJs#10]
Dont know about other projects but in angular it has become a kind of standard to use observables instead of promises.

Is there any plan to support observables instead of promises?

Angular is using rxjs for it, https://rxjs-dev.firebaseapp.com/guide/overview

**Comment by sitereactor** [comment]
Hi @kevlarAdmin there are currently no plans around observables.

**Comment by kevlarAdmin** [comment]
Okay.
