### ISSUE TITLE
Is this safe to use?

### ISSUE THREAD

**Issue by SuneRadich** [umbraco/Umbraco.Headless.Client.NodeJs#113]
It seems this is rarely updated, and the 43 Pull Requests from dependabot that have not been merged kinda puts me off using this. Can this safely be used, or is there a better alternative?

**Comment by sitereactor** [comment]
We don't have an alternative. It should be okay to use. But I agree that it needs some TLC. I will keep it in mind for a future sprint that we should get it updated and address thr dependabot PRs 😅

**Comment by sitereactor** [comment]
Well, i guess an alternative would be to use the REST API directly or our .net client library :)
