### ISSUE TITLE
Possible error with pageSize and page options, when using client.delivery.content.children

### ISSUE THREAD

**Issue by webdokkeren** [umbraco/Umbraco.Headless.Client.NodeJs#12]
Hi Umbraco, 

I stumbled upon a possible error when using options with client.delivery.content.children.
It seems to ignore pageSize and page options. 

`const children = await client.delivery.content.children(pageId, { pageSize: "20", page: "1" });`

In the above example pageSize is specified to 20 and should return 15 as there is a total for 15 children. However it only returns 10, even after setting it up in the options.

Video of the error : https://drive.google.com/file/d/1us2l65apApGPj3EFGYQeApGvz2EzoR99/view

Is this an error or am i doing something wrong ?

**Comment by sitereactor** [comment]
@webdokkeren the fix for this issue has been released on NPM: `@umbraco/headless-client@0.5.0`

Thanks for posting the issue 😄

**Comment by webdokkeren** [comment]
@sitereactor Awesome and quick work! Just pulled down the new version and now everything works as expected, cheers! :D
