### ISSUE TITLE
Lack of Documentation

### ISSUE THREAD

**Issue by flexchar** [umbraco/Umbraco.Headless.Client.NodeJs#14]
No offense but guys you don't have any documentation. List of method signatures on the README file are nearly pointless without actual examples or at least method definitions.

**Comment by sitereactor** [comment]
Hi @flexchar we do have a fair amount of documentation on our.umbraco.com/documentation/ but I do realize that its not actually linked to from anywhere in this repository. We will get that updated.

You can find API Documentation for all endpoints in both the Content Delivery and Content Management APIs here:
https://our.umbraco.com/documentation/Umbraco-Heartcore/API-Documentation/

But what you are asking for is usage documentation for the client library itself, right?

**Comment by flexchar** [comment]
I have seen these resources. However I don't find them particularly useful if I am onto using the official client. Which I believe should have in-

Ideally

**Comment by flexchar** [comment]
If you have tests, please publish the code. That would on its own provide quite decent insight 💡

**Comment by sitereactor** [comment]
Thanks for the feedback!
We have scheduled some initial work around getting better docs in place for this nodejs client library, so we should soon be able to publish some better docs.

I will update this thread when the first iteration is published.

**Comment by sitereactor** [comment]
@flexchar This has now been addressed by https://github.com/umbraco/Umbraco.Headless.Client.NodeJs/pull/17 which was just merged. The README file is updated with details. For now you will need to generate the documentation from the repository, but we are working on getting it added to the Umbraco Heartcore documentation on https://our.umbraco.com/documentation/Umbraco-Heartcore/
