### ISSUE TITLE
Support for TypeScript (typings)

### ISSUE THREAD

**Issue by tednyberg** [umbraco/Umbraco.Headless.Client.NodeJs#18]
I can't seem to find TypeScript typings for the Node client. Are there any available?

I was hoping for a `@types/@umbraco/headless-client` package, but alas - no dice. :)

**Comment by rasmusjp** [comment]
Hi @tednyberg 

The typings are included in the `@umbraco/headless-client` package.

**Comment by tednyberg** [comment]
@rasmusjp Yes, I'm an idiot. Just noticed. Sorry. :)
