### ISSUE TITLE
Descendants call should be a PagedResponse in 0.8.0

### ISSUE THREAD

**Issue by Jacob87** [umbraco/Umbraco.Headless.Client.NodeJs#38]
**Version**
0.8.0

**Description**
The `Client.delivery.content.descendants()` function seems to have the wrong typing in its return type. Typescript infers that it returns the type `Promise<Content[] | undefined>` but when invoking the function and debugging its actual output, you seem to get a PagedResponse instead. The return type should then have been inferred as `Promise<PagedResponse<Content> | undefined>` resembling that of the `children` function.

**Reference**
https://github.com/umbraco/Umbraco.Headless.Client.NodeJs/blob/3c61a2a16e0c368d8f62649785f8b52713c91c80/src/Clients/Delivery/ContentDeliveryClient.ts#L124-L126

**Comment by rasmusjp** [comment]
Hi @Jacob87 

Thanks for the repport.

 We just made a fix and pushed version 0.8.1, it should be out on npm soon.
