### ISSUE TITLE
Axios dependancy IE11 issue

### ISSUE THREAD

**Issue by tolkienosborn** [umbraco/Umbraco.Headless.Client.NodeJs#43]
Hi, 

Having an issue in ie11

'URLSearchParams' is undefined in IE 11

i believe it's to do with the Axios dependancy.

Do you have any workarounds?

**Comment by rasmusjp** [comment]
Hi @tolkienosborn 

`URLSearchParams` is part of the URL Standard specifiications and is supported by all major browsers, see https://caniuse.com/urlsearchparams. 

Unfortunately as you've noticed it isn't supported by Internet Explorer, if you need to support Internet Explorer I suggest using a polyfill e.g. https://github.com/ungap/url-search-params
